### ISSUE TITLE
server-component does not respect absolute route

### ISSUE THREAD

**Issue by ofekd** [lustre-labs/lustre#214]
Error is:

```
lustre-server-component.mjs:488 Uncaught SyntaxError: Failed to construct 'WebSocket': The URL 'ws://localhost:1234ws://localhost:8000/sessions-count' is invalid.
    at LustreServerComponent.attributeChangedCallback (lustre-server-component.mjs:488:26)
    at createElementNode (client.mjs:2795:12)
    at morph (client.mjs:2720:23)
    at #tick (client.mjs:3099:5)
    at client.mjs:3016:23
```

**Comment by hayleigh-dot-dev** [comment]
In the upcoming v5 release we now construct a `URL` directly by doing:
```
new URL(next, window.location.href);
```
which now properly supports full URLs as well as relative ones.
